---
version: "3.8"

services:
  lite:
    depends_on:
      - mysql
    env_file:
      - global-settings.env
    image: ${REGISTRY:-bitwarden}/lite:${TAG:-latest}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - bitwarden:/etc/bitwarden
      - logs:/var/log/bitwarden

  mysql:
    environment:
      MARIADB_USER: "bitwarden"
      MARIADB_PASSWORD: "super_strong_password"
      MARIADB_DATABASE: "bitwarden_vault"
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    image: mariadb:10.9.3
    restart: always
    volumes:
      - data:/var/lib/mysql

volumes:
  bitwarden:
  logs:
  data:
