---

name: _move_finalization_db_scripts
run-name: Move finalization db scripts

on:
  workflow_call:

permissions:
  pull-requests: write
  contents: write

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-22.04
    outputs:
      MIGRATION_FILENAME_PREFIX: ${{ steps.prefix.outputs.prefix }}
      COPY_FINALIZATION_SCRIPTS: ${{ steps.check-finalization-scripts-existence.outputs.copy_finalization_scripts }}
    steps:
      - name: Login to Azure
        uses: Azure/login@de95379fe4dadc2defb305917eaa7e5dde727294 # v1.5.1
        with:
          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: "bitwarden-ci"
          secrets: "github-pat-bitwarden-devops-bot-repo-scope"

      - name: Checkout Branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ steps.retrieve-secrets.outputs.github-pat-bitwarden-devops-bot-repo-scope }}

      - name: Get script prefix
        id: prefix
        run: echo "prefix=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Check if any files in db finalization
        id: check-finalization-scripts-existence
        run: |
          if [ -f util/Migrator/DbScripts_finalization/* ]; then
            echo "copy_finalization_scripts=true" >> $GITHUB_OUTPUT
          else
            echo "copy_finalization_scripts=false" >> $GITHUB_OUTPUT
          fi

  branch:
    name: Create Branch
    runs-on: ubuntu-22.04
    needs: setup
    if: ${{ needs.setup.outputs.COPY_FINALIZATION_SCRIPTS == 'true' }}
    outputs:
      deploy_branch_name: ${{ steps.branch_name.outputs.branch_name }}
      env_name: ${{ steps.branch_name.outputs.env_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Generate branch name
        id: branch_name
        env:
          PREFIX: ${{ needs.setup.outputs.MIGRATION_FILENAME_PREFIX }}
        run: echo "branch_name=move_finalization_db_scripts_$PREFIX" >> $GITHUB_OUTPUT

      - name: "Create branch"
        env:
          BRANCH: ${{ steps.branch_name.outputs.branch_name }}
        run: |
          git switch -c $BRANCH
          git push -u origin $BRANCH --force


  move-finalization-db-scripts:
    name: Move finalization db scripts
    runs-on: ubuntu-22.04
    needs:
      - setup
      - branch
    if: ${{ needs.setup.outputs.COPY_FINALIZATION_SCRIPTS == 'true' }}
    outputs:
      PR_NEEDED: ${{ steps.commit.outputs.pr_needed }}
      MOVED_FILES: ${{ steps.move-files.outputs.moved_files }}
    steps:
      - name: Login to Azure - Prod Subscription
        uses: Azure/login@de95379fe4dadc2defb305917eaa7e5dde727294 # v1.5.1
        with:
          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Checkout Branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          ref: ${{ needs.branch.outputs.deploy_branch_name }}

      - name: Move DbScripts_finalization
        id: move-files
        env:
          PREFIX: ${{ needs.setup.outputs.MIGRATION_FILENAME_PREFIX }}
        run: |
          src_dir="util/Migrator/DbScripts_finalization"
          dest_dir="util/Migrator/DbScripts"
          i=0

          moved_files=""

          for file in "$src_dir"/*; do
            filenumber=$(printf "%02d" $i)

            filename=$(basename "$file")
            new_filename="${PREFIX}_${filenumber}_${filename}"
            dest_file="$dest_dir/$new_filename"

            mv "$file" "$dest_file"

            moved_files="$moved_files /n $filename -> $new_filename"

            ((i++))
          done

          echo "moved_files=$moved_files" >> $GITHUB_OUTPUT

      - name: Retrieve GPG keys
        id: retrieve-gpg-keys
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: ${{ env._KEY_VAULT }}
          secrets: "github-gpg-private-key, github-gpg-private-key-passphrase"

      - name: Import GPG keys
        uses: crazy-max/ghaction-import-gpg@82a020f1f7f605c65dd2449b392a52c3fcfef7ef # v6.0.0
        with:
          gpg_private_key: ${{ steps.retrieve-gpg-keys.outputs.github-gpg-private-key }}
          passphrase: ${{ steps.retrieve-gpg-keys.outputs.github-gpg-private-key-passphrase }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit and push changes
        id: commit
        run: |
          git config --local user.email "${{ env._BOT_EMAIL }}"
          git config --local user.name "${{ env._BOT_NAME }}"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Move DbScripts_finalization to DbScripts" -a
            git push -u origin ${{ env._DEPLOY_BRANCH }}
            echo "pr_needed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit!";
            echo "pr_needed=false" >> $GITHUB_OUTPUT
            echo "### :mega: No changes to commit! PR was ommited." >> $GITHUB_STEP_SUMMARY
          fi

  pr:
    name: PR
    runs-on: ubuntu-22.04
    needs:
      - setup
      - branch
      - move-finalization-db-scripts
    if: ${{ needs.setup.outputs.COPY_FINALIZATION_SCRIPTS == 'true' && needs.move-finalization-db-scripts.outputs.PR_NEEDED == 'true' }}
    env:
      _KEY_VAULT: bitwarden-ci
      _BASE_BRANCH: master
      _HEAD_BRANCH: ${{ needs.branch.outputs.deploy_branch_name }}
      _PR_TITLE: "Move finalization db scripts"
      _MOVED_FILES: ${{ needs.move-finalization-db-scripts.outputs.MOVED_FILES }}
    outputs:
      pr_url: ${{ steps.create-pr.outputs.pr_url }}
    steps:
      - name: Login to Azure - Prod Subscription
        uses: Azure/login@de95379fe4dadc2defb305917eaa7e5dde727294 # v1.5.1
        with:
          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Checkout Branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Create PR for ${{ env._HEAD_BRANCH }}
        id: create-pr
        run: |
          PR_URL=$(gh pr create --title "${{ env._PR_TITLE }}" \
            --base "${{ env._BASE_BRANCH }}" \
            --head "${{ env._HEAD_BRANCH }}" \
            --label "automated pr" \
            --body "
              ## Automated movement of DbScripts_finalization to DbScripts

              ## Files moved:
              $(echo -e "$_MOVED_FILES")
              ")
          echo "pr_url=${PR_URL}" >> $GITHUB_OUTPUT

  notify:
    name: Notify about PR
    if: ${{ needs.setup.outputs.COPY_FINALIZATION_SCRIPTS == 'true' && needs.move-finalization-db-scripts.outputs.PR_NEEDED == 'true' }}
    runs-on: ubuntu-22.04
    needs:
      - setup
      - branch
      - move-finalization-db-scripts
      - pr
    steps:
      - name: Login to Azure - CI subscription
        uses: Azure/login@de95379fe4dadc2defb305917eaa7e5dde727294 # v1.5.1
        with:
          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: "bitwarden-ci"
          secrets: "devops-alerts-slack-webhook-url"

      - name: Notify Slack about creation of PR
        uses: act10ns/slack@ed1309ab9862e57e9e583e51c7889486b9a00b0f # v2.0.0
        env:
          SLACK_WEBHOOK_URL: ${{ steps.retrieve-secrets.outputs.devops-alerts-slack-webhook-url }}
        with:
          message: "TEST: Created PR for moving DbScripts_finalization to DbScripts: ${{ needs.pr.outputs.pr_url }}"
