---
name: Build

on:
  push:
    branches-ignore:
      - 'l10n_master'
      - 'gh-pages'
    paths:
      - 'src/Sql/**'
      - 'util/Migrator/**'
  workflow_dispatch:
    inputs: {}

jobs:
  databse:
    name: Build DACPAC
    runs-on: windows-2022
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Set up dotnet
        uses: actions/setup-dotnet@9211491ffb35dd6a6657ca4f45d43dfe6e97c829
        with:
          dotnet-version: '6.0.x'
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@ab534842b4bdf384b8aaf93765dc6f721d9f5fab

      - name: Print environment
        run: |
          dotnet --info
          msbuild -version
          nuget help | grep Version
          echo "GitHub ref: $GITHUB_REF"
          echo "GitHub event: $GITHUB_EVENT"

      - name: Checkout repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Build DACPAC
        run: msbuild src/Sql/Sql.sqlproj /p:Configuration=Release /verbosity:minimal
        shell: pwsh

      - name: Upload DACPAC
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: Sql.dacpac
          path: src/Sql/bin/Release/Sql.dacpac
