---
name: Clean After PR

on:
  pull_request:
    types: [closed]
  workflow_dispatch: 
    inputs: {}

jobs:
  build-docker:
    name: Remove feature branch docker images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      ########## ACR ##########
      - name: Login to Azure - QA Subscription
        uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
        with:
          creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Login to Azure ACR
        run: az acr login -n bitwardenqa

      ########## Build Docker Image ##########
      - name: Setup service name
        id: setup
        run: |
          SERVICE_NAME=$(echo "${{ matrix.service_name }}" | awk '{print tolower($0)}')
          echo "Matrix name: ${{ matrix.service_name }}"
          echo "SERVICE_NAME: $SERVICE_NAME"
          echo "::set-output name=service_name::$SERVICE_NAME"

      - name: Remove the docker image from ACR
        env:
          REGISTRY: bitwardenqa.azurecr.io
          SERVICES: |
            services:
              - Admin
              - Api
              - Attachments
              - Events
              - EventsProcessor
              - Icons
              - Identity
              - K8S-Proxy
              - MsSql
              - Nginx
              - Notifications
              - Server
              - Setup
              - Sso
        run: |
          for SERVICE in $(echo "${{ env.SERVICES }}" | yq e ".services[]" - )
          do
            SERVICE_NAME=$(echo $SERVICE | awk '{print tolower($0)}')
            IMAGE_TAG=$(echo "${GITHUB_REF:11}" | sed "s#/#-#g")  # slash safe branch name

            if [[ "$IMAGE_TAG" == "master" ]]; then
              IMAGE_TAG=dev
            fi

            echo "az acr repository delete --name $REGISTRY --image $SERVICE_NAME:$IMAGE_TAG --yes"
          done

      - name: Log out of Docker
        run: docker logout
