---
name: Clean After PR

on:
  pull_request:
    - closed

jobs:
  build-docker:
    name: Remove docker images no longer needed
    runs-on: ubuntu-20.04
    needs: build-artifacts
    strategy:
      fail-fast: false
      matrix:
        include:
          - service_name: Admin
          - service_name: Api
          - service_name: Attachments
          - service_name: Events
          - service_name: EventsProcessor
          - service_name: Icons
          - service_name: Identity
          - service_name: K8S-Proxy
          - service_name: MsSql
          - service_name: Nginx
          - service_name: Notifications
          - service_name: Server
          - service_name: Setup
          - service_name: Sso
    steps:
      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      ########## Build Docker Image ##########
      - name: Setup service name
        id: setup
        run: |
          SERVICE_NAME=$(echo "${{ matrix.service_name }}" | awk '{print tolower($0)}')
          echo "Matrix name: ${{ matrix.service_name }}"
          echo "SERVICE_NAME: $SERVICE_NAME"
          echo "::set-output name=service_name::$SERVICE_NAME"

      ########## ACR ##########
      - name: Login to Azure - QA Subscription
        uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
        with:
          creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Login to Azure ACR
        run: az acr login -n bitwardenqa

      - name: Remove the docker image from ACR
        env:
          REGISTRY: bitwardenqa.azurecr.io
        run: |
          IMAGE_TAG=$(echo "${GITHUB_REF:11}" | sed "s#/#-#g")  # slash safe branch name
          if [[ "$IMAGE_TAG" == "master" ]]; then
            IMAGE_TAG=dev
          fi

          az acr repository delete --name $REGISTRY --image ${{ steps.setup.outputs.service_name }}:$IMAGE_TAG

      - name: Log out of Docker
        run: docker logout
