---
name: Collect code references

on:
  pull_request:
    branches-ignore:
      - "renovate/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  refs:
    name: Code reference collection
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Collect
        id: collect
        uses: launchdarkly/find-code-references-in-pull-request@d008aa4f321d8cd35314d9cb095388dcfde84439 # v2.0.0
        with:
          project-key: default
          environment-key: dev
          access-token: ${{ secrets.LD_ACCESS_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add label
        if: steps.collect.outputs.any-changed == 'true'
        run: gh pr edit $PR_NUMBER --add-label feature-flag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Remove label
        if: steps.collect.outputs.any-changed == 'false'
        run: gh pr edit $PR_NUMBER --remove-label feature-flag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
