---
name: "Pull Request Labeler"
on:
  pull_request:
    types:
      - opened

jobs:
  # Applies the community-pr label to any PRs from a forked repo, which is used as a proxy for a community PR
  community-pr:
    name: 'Label community PRs'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - if: ${{ github.event.pull_request.head.repo.fork }}
        name: 'Apply label'
        uses: actions/labeler@9fd24f1f9d6ceb64ba34d181b329ee72f99978a0  # v4.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/workflows/community-pr-label.yml"
