---

name: Protect Files

on:
  pull_request:
    types: [opened, edited, synchronize]
    paths: ["util/Migrator/DbScripts"]

jobs:
  changed-files:
    name: Check for file changes
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Database Scripts
            path: util/Migrator/DbScripts
    steps:
      - name: Checkout PR
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          fetch-depth: 0

      - name: Check for file changes
        run: |
          if [ -z "$(git diff --name-only HEAD)" ]; then
            echo "No files changed"
            exit 0
          fi
          echo "Files changed"
          exit 1





