name: Success Caching

on:
  push:
    branches:
      - master
  workflow_dispatch: 
    inputs: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Log date
        run: echo "${{ steps.date.outputs.date }}"

      - name: Set default run status
        run: echo "default" > last_run_status

      - name: Restore last 
        id: last_run
        uses: actions/cache@v2
        with:
          path: |
            last_run_status
          key: ${{ github.run_id }}-${{ steps.date.outputs.date }}
          restore-keys:
            ${{ github.run_id }}-

      - name: Set last run status
        id: last_run_status
        run: echo "::set-output name=last_run_status::$(cat last_run_status)"

      - name: Randomly succeed or fail
        id: run_task
        run: |
          STATUS_NUM=$(( $RANDOM % 5 + 1 ))
          echo "Status: $STATUS_NUM"
          if [[ $STATUS_NUM -nq 1 ]]; then 
            exit 1
          fi
          echo "::set-output name=status::$STATUS_NUM"

      - name: Set status
        if: always()
        #if: steps.last_run_status.outputs.last_run_status != "success"
        run: |
          echo "Last run status: ${{ steps.last_run_status.outputs.last_run_status }}"
          STATUS_NUM=${{ steps.runtask.outputs.status }}
          echo "Status: $STATUS_NUM"

          if [[ $STATUS_NUM -eq 1 ]]; then 
            echo "success" > last_run_status
            cat last_run_status
          else
            echo "fail" > last_run_status
            cat last_run_status
          fi
